version: '3.1'

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: widgets
      MYSQL_USER: widgets
      MYSQL_PASSWORD: widgets
    volumes:
      - msdata:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  msdata:
    driver: local