# Use root/secret as user/password credentials
version: '3.1'

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    ports:
      - "3306:3306"